import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh]`}
      >
        <div className="h-[100%]  w-[100%]">
          <div className="app-bar shadow-lg gap-2 p-7 top-0 w-[100%]border-b-orange-800 bg-gray-100 h-[1%] flex items-center justify-between ">
            <div className="font-[family-name:var(--font-geist-sans)]">
              <h1>Medium</h1>
            </div>
            <ul className="flex justify-center gap-4 font-[family-name:var(--font-geist-sans)] ">
              <li>Home</li>
              <li>About</li>
              <li>Contect</li>
              <li>Sign In | Sign up</li>
            </ul>

          </div>

          <div className="h-[100%] w-[100%]">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
